name: Release Creation

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Package Module
        run: |
          zip -r module.zip module.json screen-share.js src/ README.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            module.zip
            module.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
